#!/usr/bin/python
import time
import requests
import json
print ('Hello')
url = 'http://localhost:8080/secure/person/1'
headers = {'Content-type': 'application/json', 'X-Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxTSIsInNjb3BlcyI6eyJpZCI6MSwic3RhdHVzIjoiQUNUIiwidXNlck5hbWUiOiIxTSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwic3lzdGVtT3duZXIiOnRydWUsInBlcnNvbiI6bnVsbCwiZXh0ZXJuYWxQZXJzb24iOm51bGwsImhlYWx0aENlbnRlckhhc09wZXJhdG9yIjpbeyJpZCI6MSwic3RhdHVzIjoiQUNUIiwiaGVhbHRoQ2VudGVyIjp7ImlkIjoxLCJuYXRpb25hbENvZGUiOiIxIiwiaW50ZXJuYWxDb2RlIjoiMSIsImFkZHJlc3MiOiJTYW4gUmFmYWVsIiwibmFtZSI6IkhPU1BJVEFMIFNDSEVTVEFLT1ciLCJwaG9uZSI6IjEiLCJ3b3JraW5nSG91cnMiOiIyNCIsInN0YXR1cyI6IkFDVCIsImlzUHVibGljIjoiMSIsImlzUGxhbm5pbmciOnRydWV9fSx7ImlkIjoyLCJzdGF0dXMiOiJBQ1QiLCJoZWFsdGhDZW50ZXIiOnsiaWQiOjIsIm5hdGlvbmFsQ29kZSI6IjIzNDU2IiwiaW50ZXJuYWxDb2RlIjoiMjMxIiwiYWRkcmVzcyI6IlNhbiBSYWZhZWwiLCJuYW1lIjoiUE9MSUNMSU5JQ0EgU0FOIFJBRkFFTCIsInBob25lIjoiMTIzNCIsIndvcmtpbmdIb3VycyI6IjAwOjAwLTI0OjAwIiwic3RhdHVzIjoiQUNUIiwiaXNQdWJsaWMiOiIxIiwiaXNQbGFubmluZyI6dHJ1ZX19LHsiaWQiOjMsInN0YXR1cyI6IkFDVCIsImhlYWx0aENlbnRlciI6eyJpZCI6MywibmF0aW9uYWxDb2RlIjoiMDM1MDAwNSIsImludGVybmFsQ29kZSI6IjAzNTAwMDUiLCJhZGRyZXNzIjoiTWFsYXJnw7xlIiwibmFtZSI6IkhPU1BJVEFMIE1BTEFSR8OcRSIsInBob25lIjoiMjY1Ny00MjE0MTUiLCJ3b3JraW5nSG91cnMiOiIwMDowMC0yNDowMCIsInN0YXR1cyI6IkFDVCIsImlzUHVibGljIjoiMSIsImlzUGxhbm5pbmciOnRydWV9fV0sImZsYWdzIjpudWxsfSwiaXNzIjoiaHR0cDovL3N0YWNrdHJhY2UuY29tLmFyIiwiaWF0IjoxNTYwMzgxODQ5LCJleHAiOjE1NjA0MTA2NDl9.H1QF3gu_MkFXNr5IhWVaux2iD3XRfgbBvxXc2ebr65aVyEsVLfi3jpgwMBk_KD-gVqvXYd31UxbfjhxE3v26mA'}
response = requests.get(url, headers=headers)
# parse x:
y = json.loads(response.text)
# the result is a Python dictionary:
print(y[0]['authToken'])
print ("End : %s" % response.status_code)
